"""add scenarios decisions simulation_runs

Revision ID: 812f47a4f6a5
Revises: 7120ef3f504e
Create Date: 2026-03-23 12:37:02.533668
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '812f47a4f6a5'
down_revision = '7120ef3f504e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('lag_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ramp_months', sa.Integer(), server_default='1', nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_decisions_id'), 'scenario_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_decisions_scenario_id'), 'scenario_decisions', ['scenario_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_scenario_id'), 'simulation_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_user_id'), 'simulation_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_runs_user_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_scenario_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_scenario_decisions_scenario_id'), table_name='scenario_decisions')
    op.drop_index(op.f('ix_scenario_decisions_id'), table_name='scenario_decisions')
    op.drop_table('scenario_decisions')
    # ### end Alembic commands ###
